const ALERT = "ALERT";
const REFETCH_CHATS =  "REFETCH_CHATS"
const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT"
const NEW_ATTACHMENT_ALERT = "NEW_ATTACHMENT_ALERT"


export {
    ALERT,
    REFETCH_CHATS,
    NEW_MESSAGE_ALERT,
    NEW_ATTACHMENT_ALERT
}